services:
  api:
    container_name: dev_api
    ports: 
      - 3000:3000
    environment: 
      - DB_NAME=habits
      - DB_CONNECTION=mongodb://hiho:hihopass@db:27017
    depends_on:
      - db
    command: bash -c "npm install && npm run start"
  db:
    container_name: dev_db
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      #- "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=hiho
      - MONGO_INITDB_DATABASE=habits
      - MONGO_INITDB_ROOT_PASSWORD=hihopass
volumes:
  dbdata:
networks: 
  default:
    name: app_dev
